run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      hostname:
        env: POSTGRES_HOST
      port:
        env: POSTGRES_PORT
      username:
        env: POSTGRES_USER
      password:
        env: POSTGRES_PASSWORD
      db_name:
        env: POSTGRES_DB
      params:
        keepalives: 1
        keepalives_idle: 30
        keepalives_interval: 10
        keepalives_count: 5
        connect_timeout: 10

event_log_storage:
  module: dagster_postgres.event_log
  class: PostgresEventLogStorage
  config:
    postgres_db:
      hostname:
        env: POSTGRES_HOST
      port:
        env: POSTGRES_PORT
      username:
        env: POSTGRES_USER
      password:
        env: POSTGRES_PASSWORD
      db_name:
        env: POSTGRES_DB
      params:
        keepalives: 1
        keepalives_idle: 30
        keepalives_interval: 10
        keepalives_count: 5
        connect_timeout: 10

schedule_storage:
  module: dagster_postgres.schedule_storage
  class: PostgresScheduleStorage
  config:
    postgres_db:
      hostname:
        env: POSTGRES_HOST
      port:
        env: POSTGRES_PORT
      username:
        env: POSTGRES_USER
      password:
        env: POSTGRES_PASSWORD
      db_name:
        env: POSTGRES_DB
      params:
        keepalives: 1
        keepalives_idle: 30
        keepalives_interval: 10
        keepalives_count: 5
        connect_timeout: 10

run_launcher:
  module: dagster._core.launcher
  class: DefaultRunLauncher

run_monitoring:
  enabled: true
  poll_interval_seconds: 120
  max_resume_run_attempts: 0
  start_timeout_seconds: 300
  cancel_timeout_seconds: 300

concurrency:
  runs:
    max_concurrent_runs: 20
    tag_concurrency_limits:
      - key: "dagster/concurrency_limit"
        value: "matchmaking"
        limit: 5
      - key: "dagster/job_name"
        value: "candidate_pipeline"
        limit: 15

telemetry:
  enabled: false
